// WARNING: This file was autogenerated by MBRS generator.
// Do not update it because if you run generator again you changes will be deleted

package ftn.backendservice.controllers;

import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.ResponseEntity;

import ftn.backendservice.domain.entities.BankBranch;
import ftn.backendservice.services.BankBranchService;


@RestController
@RequestMapping("/api/bankBranch")
@RequiredArgsConstructor
public class BankBranchController {

    private final BankBranchService bankBranchService;

    @GetMapping("{id}")
    public ResponseEntity<?> getById(@PathVariable Long id) {
        return ResponseEntity.ok(bankBranchService.getById(id));
    }

    @GetMapping(value = "/all")
    public ResponseEntity<?> getAll() {
        return ResponseEntity.ok(bankBranchService.getAll());
    }

    @PostMapping(value = "/create")
    public ResponseEntity<?> create(@RequestBody BankBranch request) {
        return ResponseEntity.ok(bankBranchService.save(request));
    }

    @PutMapping("/{id}")
    public ResponseEntity<?> update(@PathVariable Long id, @RequestBody BankBranch updateRequest) {
        return ResponseEntity.ok(bankBranchService.update(updateRequest));
    }

}