// WARNING: This file was autogenerated by MBRS generator.
// Do not update it because if you run generator again you changes will be deleted

package ftn.backendservice.domain.mappers;

import org.mapstruct.*;
import org.mapstruct.factory.Mappers;

import java.util.List;

import ftn.backendservice.domain.dtos.AccountDto;
import ftn.backendservice.domain.entities.*;


@Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE,
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public interface AccountMapper {

    AccountMapper INSTANCE = Mappers.getMapper(AccountMapper.class);

    @Mapping(source = "customer.id", target = "customerId")
    @Mapping(target = "transactionIds", expression = "java(account.getTransactions().stream().map(ftn.backendservice.domain.entities.Transaction::getId).collect(java.util.stream.Collectors.toList()))")
    AccountDto toDTO(Account account);

    List<AccountDto> toDTO(List<Account> account);

}
