// WARNING: This file was autogenerated by MBRS generator.
// Do not update it because if you run generator again you changes will be deleted

package ftn.backendservice.domain.entities;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Getter;
import lombok.Setter;
import org.springframework.format.annotation.DateTimeFormat;

import jakarta.persistence.*;
import java.util.HashSet;
import java.util.Date;
import java.time.LocalDateTime;
import java.util.Set;
import java.util.List;

@Entity
@Table(name = "AccountTable")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Account {
    
    @Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;
    
    @Column(name = "accountNumber", nullable = true, unique = false)
    private String accountNumber;
    
    @Column(name = "balance", nullable = false, unique = false)
    private Double balance;
    
    @ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id")
    private Customer customer;
    
    @OneToMany(cascade = CascadeType.PERSIST)
	@JoinColumn(name = "account_id")
    private List<Transaction> transactions;
    
}