// WARNING: This file was autogenerated by MBRS generator.
// Do not update it because if you run generator again you changes will be deleted

package ftn.backendservice.domain.entities;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Getter;
import lombok.Setter;
import org.springframework.format.annotation.DateTimeFormat;

import jakarta.persistence.*;
import java.util.HashSet;
import java.util.Date;
import java.time.LocalDateTime;
import java.util.Set;
import java.util.List;

@Entity
@Table(name = "CustomerTable")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Customer {
    
    @Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;
    
    @Column(name = "name", nullable = false, unique = false)
    private String name;
    
    @Column(name = "surname", nullable = false, unique = false)
    private String surname;
    
    @OneToMany(cascade = CascadeType.PERSIST)
	@JoinColumn(name = "customer_id")
    private List<Account> accounts;
    
    @Column(name = "email", nullable = false, unique = false)
    private String email;
    
    @ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bankBranch_id")
    private BankBranch bankBranch;
    
}