// WARNING: This file was autogenerated by MBRS generator.
// Do not update it because if you run generator again you changes will be deleted

package ftn.backendservice.domain.entities;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Getter;
import lombok.Setter;
import org.springframework.format.annotation.DateTimeFormat;

import jakarta.persistence.*;
import java.util.HashSet;
import java.util.Date;
import java.time.LocalDateTime;
import java.util.Set;
import java.util.List;

@Entity
@Table(name = "TransactionTable")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Transaction {
    
    @Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;
    
    @Column(name = "amount", nullable = false, unique = false)
    private Double amount;
    
    @Column(name = "transactionDate", nullable = false, unique = false)
    private LocalDateTime transactionDate;
    
}